### ISSUE TITLE
Connect via Bluetooth

### ISSUE THREAD

**Issue by grumpyprogrammingracoon** [tim479874/cont-laser-meas#1]
Hello, Tried connecting to my trupulse TP360 via bluetooth using bluetoothctl but the connection failed.
You got any hints to establish a Bluetooth Connection via Linux CLI?

**Comment by tim479874** [comment]
Hi.
Pair it via bluetoothctl. Trust it. And then establishe the connection via rfcomm with root rights.
`sudo rfcomm connect /dev/rfcommX <MAC> 1 &`
See also here: [https://askubuntu.com/questions/248817/how-to-i-connect-a-raw-serial-terminal-to-a-bluetooth-connection]([https://askubuntu.com/questions/248817/how-to-i-connect-a-raw-serial-terminal-to-a-bluetooth-connection)

Now the connection should be established and you can start the programm. Again start the script with root rights. 
`sudo python3 tp_pm.py` and enter the Port as `/dev/rfcommX`

Be sure to update the script as I deleted an unwanted line today.

Hope it helped.
